from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from pymia.contracts.evidence_availability_v1 import (
    EvidenceAvailabilityStatus,
    allows_calculation,
    blocks_required_field,
    default_status_for_reason,
    is_excluded_from_calculation,
    requires_owner_disclosure as availability_requires_owner_disclosure,
)
from pymia.contracts.evidence_warning_v1 import (
    EvidenceWarningSeverity,
    blocks_calculation as warning_blocks_calculation,
    default_severity_for_reason,
    is_owner_message_allowed,
    requires_owner_disclosure as warning_requires_owner_disclosure,
)

ExpectedEvidenceType = Literal["text", "number", "integer", "boolean"]


@dataclass(frozen=True)
class EvidenceWarning:
    warning_id: str
    severity: EvidenceWarningSeverity
    source_field: str
    reason_code: str
    owner_message: str
    operator_detail: str
    blocks_calculation: bool
    suggested_next_evidence: str


@dataclass(frozen=True)
class NormalizedEvidenceValue:
    field_name: str
    expected_type: ExpectedEvidenceType
    raw_value: Any
    normalized_value: Any
    availability_status: EvidenceAvailabilityStatus
    reason_code: str
    warnings: list[EvidenceWarning]
    excluded_from_calculation: bool
    blocks_required_field: bool
    allows_calculation: bool
    requires_owner_disclosure: bool


def normalize_evidence_value(
    *,
    raw_value: Any,
    field_name: str,
    expected_type: ExpectedEvidenceType,
    required: bool = False,
) -> NormalizedEvidenceValue:
    """Normalize one raw evidence value without touching runtime or diagnostic flow.

    This service only classifies one value. It does not read files, infer business
    truth, calculate formulas, diagnose, persist, or call pipelines.
    """
    normalized_field_name = _required_text(field_name, field_name="field_name")
    normalized_expected_type = _validate_expected_type(expected_type)

    normalized_value, reason_code = _normalize_raw_value(
        raw_value=raw_value,
        expected_type=normalized_expected_type,
    )
    status = default_status_for_reason(reason_code)
    if status is None:
        raise ValueError(f"Unsupported reason_code generated by normalizer: {reason_code}")

    warnings = _build_warnings(
        field_name=normalized_field_name,
        reason_code=reason_code,
        availability_status=status,
        required=required,
    )

    return NormalizedEvidenceValue(
        field_name=normalized_field_name,
        expected_type=normalized_expected_type,
        raw_value=raw_value,
        normalized_value=normalized_value,
        availability_status=status,  # type: ignore[arg-type]
        reason_code=reason_code,
        warnings=warnings,
        excluded_from_calculation=is_excluded_from_calculation(status),
        blocks_required_field=bool(required and blocks_required_field(status)),
        allows_calculation=allows_calculation(status),
        requires_owner_disclosure=availability_requires_owner_disclosure(status)
        or any(warning.requires_owner_disclosure if hasattr(warning, "requires_owner_disclosure") else False for warning in []),
    )


def _normalize_raw_value(*, raw_value: Any, expected_type: ExpectedEvidenceType) -> tuple[Any, str]:
    if raw_value is None:
        return None, "MISSING_FIELD"

    if isinstance(raw_value, str) and not raw_value.strip():
        return None, "MISSING_FIELD"

    if expected_type == "text":
        if isinstance(raw_value, str):
            return raw_value.strip(), "OBSERVED_VALUE"
        return str(raw_value).strip(), "OBSERVED_VALUE"

    if expected_type == "number":
        return _normalize_number(raw_value)

    if expected_type == "integer":
        return _normalize_integer(raw_value)

    if expected_type == "boolean":
        return _normalize_boolean(raw_value)

    raise ValueError(f"Unsupported expected_type: {expected_type}")


def _normalize_number(raw_value: Any) -> tuple[float | int | None, str]:
    if isinstance(raw_value, bool):
        return None, "AMBIGUOUS_FORMAT"
    if isinstance(raw_value, int | float):
        if raw_value == 0:
            return raw_value, "OBSERVED_ZERO"
        return raw_value, "OBSERVED_VALUE"
    if isinstance(raw_value, str):
        value = raw_value.strip()
        if not value:
            return None, "MISSING_FIELD"
        cleaned = value.replace(" ", "")
        if cleaned.count(",") == 1 and cleaned.count(".") == 0:
            cleaned = cleaned.replace(",", ".")
        elif cleaned.count(",") > 0 and cleaned.count(".") > 0:
            return None, "AMBIGUOUS_FORMAT"
        try:
            parsed = float(cleaned)
        except ValueError:
            return None, "AMBIGUOUS_FORMAT"
        if parsed == 0:
            return 0, "OBSERVED_ZERO"
        return parsed, "OBSERVED_VALUE"
    return None, "AMBIGUOUS_FORMAT"


def _normalize_integer(raw_value: Any) -> tuple[int | None, str]:
    normalized_number, reason_code = _normalize_number(raw_value)
    if reason_code != "OBSERVED_VALUE" and reason_code != "OBSERVED_ZERO":
        return None, reason_code
    if isinstance(normalized_number, float) and not normalized_number.is_integer():
        return None, "AMBIGUOUS_FORMAT"
    return int(normalized_number), reason_code


def _normalize_boolean(raw_value: Any) -> tuple[bool | None, str]:
    if isinstance(raw_value, bool):
        return raw_value, "OBSERVED_VALUE"
    if isinstance(raw_value, str):
        value = raw_value.strip().lower()
        if not value:
            return None, "MISSING_FIELD"
        if value in {"true", "yes", "si", "sí", "1"}:
            return True, "OBSERVED_VALUE"
        if value in {"false", "no", "0"}:
            return False, "OBSERVED_VALUE"
    return None, "AMBIGUOUS_FORMAT"


def _build_warnings(
    *,
    field_name: str,
    reason_code: str,
    availability_status: str,
    required: bool,
) -> list[EvidenceWarning]:
    severity = default_severity_for_reason(reason_code)
    if severity is None:
        return []
    if severity == "INFO":
        return []

    owner_message = _owner_message_for_reason(reason_code=reason_code, required=required)
    if not is_owner_message_allowed(owner_message):
        raise ValueError("Generated owner_message violates evidence warning policy")

    return [
        EvidenceWarning(
            warning_id=f"{field_name}:{reason_code}",
            severity=severity,  # type: ignore[arg-type]
            source_field=field_name,
            reason_code=reason_code,
            owner_message=owner_message,
            operator_detail=f"field={field_name}; reason_code={reason_code}; availability_status={availability_status}",
            blocks_calculation=warning_blocks_calculation(severity),
            suggested_next_evidence=_suggested_next_evidence_for_reason(reason_code),
        )
    ]


def _owner_message_for_reason(*, reason_code: str, required: bool) -> str:
    if reason_code in {"MISSING_FIELD", "MISSING_SOURCE"}:
        if required:
            return "Falta un dato necesario para calcular con seguridad."
        return "No se pudo determinar este dato con la evidencia actual."
    if reason_code == "PARTIAL_SOURCE":
        return "Este dato surge de evidencia parcial."
    if reason_code == "COVERAGE_CAPPED":
        return "Este dato puede estar limitado por cobertura o truncamiento de extracción."
    if reason_code in {"AMBIGUOUS_FORMAT", "AMBIGUOUS_MEANING"}:
        return "Este dato es ambiguo y no se usó para calcular."
    if reason_code in {"EXCLUDED_BY_RULE", "EXCLUDED_LOW_CONFIDENCE"}:
        return "Este dato fue excluido del cálculo por una regla de calidad de evidencia."
    return "Hay una advertencia sobre este dato."


def _suggested_next_evidence_for_reason(reason_code: str) -> str:
    if reason_code in {"MISSING_FIELD", "MISSING_SOURCE"}:
        return "Aportar una fuente donde ese dato esté visible."
    if reason_code in {"AMBIGUOUS_FORMAT", "AMBIGUOUS_MEANING"}:
        return "Aclarar el significado o formato del dato."
    if reason_code in {"PARTIAL_SOURCE", "COVERAGE_CAPPED"}:
        return "Aportar una fuente más completa o sin truncamiento."
    if reason_code in {"EXCLUDED_BY_RULE", "EXCLUDED_LOW_CONFIDENCE"}:
        return "Aportar una fuente alternativa o corregida."
    return "Aportar evidencia adicional si corresponde."


def _validate_expected_type(expected_type: ExpectedEvidenceType) -> ExpectedEvidenceType:
    if expected_type not in {"text", "number", "integer", "boolean"}:
        raise ValueError("expected_type is unsupported")
    return expected_type


def _required_text(value: str, *, field_name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field_name} is required and must be a non-empty string")
    return value.strip()


__all__ = [
    "EvidenceWarning",
    "ExpectedEvidenceType",
    "NormalizedEvidenceValue",
    "normalize_evidence_value",
]
